title: Jaemin Choi's blog
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
# baseurl: "/flexible-jekyll" # the subpath of your site, e.g. /blog
baseurl: ""
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Author Settings 
author: Jaemin Choi # add your name
author-img: Capybara.jpeg # add your photo
about-author: Signal and Processing, AI paper review and implmentation. # add description
social-github: jaeminld # add your Github handle
social-linkedin: # add your Linkedin handle

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Menu bar
nav:
  - name: "Home"
    url: "/"
  - name: "Home"
    url: "/"
  - name: "Category"
    url: "/Category/"
  - name: "About"
    url: "/About/"


# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
